USE [ETRADE4]
GO

/****** Object:  View [dbo].[IlBazlliSiparisSayisi]    Script Date: 9.10.2023 20:49:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[IlBazlliSiparisSayisi]
as
SELECT top 100000000

COUNT(DISTINCT U.ID) KULLANÝCÝ_SAYÝSÝ,
CT.CITY ÝL, CAST(SUM(O.TOTALPRICE) AS DECIMAL(30,2)) TOPLAM_SÝPARÝS_TUTARÝ 

FROM ORDERS O

INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID

GROUP BY  CT.CITY

ORDER BY COUNT(U.ID) DESC
GO


